//
// Created by USUARIO on 24/05/2026.
//

#ifndef PROYECTOFINAL_ANALISIS_H
#define PROYECTOFINAL_ANALISIS_H
#include "Programa.h"
#include <iostream>

#include "Comparacion.h"
#include "Hecho.h"

// Analisis estatico: inspecciona el AST sin ejecutarlo.

class Analisis {
    public:

    // Conflicto: una misma accion generada por mas de una regla.

    void detectarConflictos(Programa& programa) {
        unordered_map<string, vector<string>> accionAReglas;
        for (const auto& regla : programa.reglas) {
            accionAReglas[regla->accion].push_back(regla->nombre);
        }
        for (const auto& par : accionAReglas) {
            if (par.second.size() > 1) {
                cout << "Action " << par.first << " generated by ";
                for (size_t i = 0; i < par.second.size(); i++) {
                    cout << par.second[i];
                    if (i < par.second.size() - 1) cout << ", ";
                }
                cout << endl;
            }
        }
    }

    // Redundancia: dos reglas con misma condicion y misma accion (compara por aTexto).

    void detectarRedundancias(Programa& programa) {
        for (size_t i = 0; i < programa.reglas.size(); i++) {
            for (size_t j = i + 1; j < programa.reglas.size(); j++) {
                string firmaI = programa.reglas[i]->condicion->aTexto() + "=>" + programa.reglas[i]->accion;
                string firmaJ = programa.reglas[j]->condicion->aTexto() + "=>" + programa.reglas[j]->accion;
                if (firmaI == firmaJ) {
                    cout << "Redundant rules: " << programa.reglas[i]->nombre
                         << ", " << programa.reglas[j]->nombre << endl;
                }
            }
        }
    }

    // Regla inactiva: condicion que nunca puede volverse verdadera.
    // Comparacion falsa en el estado inicial, o hecho que nada puede activar.

    void detectarInactivas(Programa& programa, unordered_map<string,int>& variables, unordered_set<string>& hechosIniciales) {

        unordered_set<string> activables = hechosIniciales;
        for (const auto& regla : programa.reglas) {
            activables.insert(regla->accion);
        }

        for (const auto& regla : programa.reglas) {
            Condicion* c = regla->condicion.get();


            Comparacion* comp = dynamic_cast<Comparacion*>(c); // ¿es comparacion?
            if (comp != nullptr) {
                if (!comp->evaluar(variables, hechosIniciales)) {
                    cout << "Potentially inactive rule: " << regla->nombre << endl;
                }
                continue;
            }


            Hecho* h = dynamic_cast<Hecho*>(c); // ¿es hecho?
            if (h != nullptr && activables.count(h->identificador) == 0) {
                cout << "Potentially inactive rule: " << regla->nombre << endl;
            }
        }
    }
};


#endif //PROYECTOFINAL_ANALISIS_H